openapi: 3.0.0
info:
  title: FactSet Formula API
paths:
  /v1/time-series:
    get:
      summary: >-
        Retrieve data items (FQL formulas) for a list of identifiers or defined
        universe.
      description: >
        The `/time-series` endpoint is closely aligned with FactSet’s powerful
        data retrieval language **FactSet Query Language (FQL)** which is
        optimized for time-series analysis. FQL can also perform sophisticated
        statistical, mathematical, logical, and other complex operations on the
        data.

          This endpoint has a unique **TIMESERIES** data object that pairs the requested data with FactSet provided dates. This helps reduce the need for additional data requests and reduces the work required by users.

        The `/time-series` endpoint supports Long Running asynchronous requests
        up to **20 minutes** via the `batch` parameter. *This feature is
        available to Individual Users subscribed to the Performance Package and
        Performance Package Plus Performance Tiers and all Production Users. If
        you are unsure which Performance Tier you are subscribed to or you would
        like to gain access to the batch capabilities, please contact your
        FactSet Account Team or "Report Issue" above and our support teams can
        assist.*
      tags:
        - Retrieve
        - Data
        - Items
        - Formulas)
        - For
        - List
        - Of
        - Identifiers
        - Or
        - Defined
        - Universe.
        - V1
        - Time
        - Series
    post:
      summary: >-
        Retrieve data items (FQL formulas) for a list of identifiers or defined
        universe.
      description: >
        The `/time-series` endpoint is closely aligned with FactSet’s powerful
        data retrieval language **FactSet Query Language (FQL)** which is
        optimized for time-series analysis. FQL can also perform sophisticated
        statistical, mathematical, logical, and other complex operations on the
        data.

          This endpoint has a unique **TIMESERIES** data object that pairs the requested data with FactSet provided dates. This helps reduce the need for additional data requests and reduces the work required by users.

        The `/time-series` endpoint supports Long Running asynchronous requests
        up to **20 minutes** via the `batch` parameter. *This feature is
        available to Individual Users subscribed to the Performance Package and
        Performance Package Plus Performance Tiers and all Production Users. If
        you are unsure which Performance Tier you are subscribed to or you would
        like to gain access to the batch capabilities, please contact your
        FactSet Account Team or "Report Issue" above and our support teams can
        assist.*
      tags:
        - Retrieve
        - Data
        - Items
        - Formulas)
        - For
        - List
        - Of
        - Identifiers
        - Or
        - Defined
        - Universe.
        - V1
        - Time
        - Series
  /v1/cross-sectional:
    get:
      summary: >-
        Retrieve data items (Screening formulas) for a list of identifiers or
        defined universe.
      description: >
        The `/cross-sectional` endpoint is closely aligned with FactSet’s
        powerful data retrieval **Screening language** which is optimized for
        analysis of data items at single point in time for different entities
        and is extremely efficient for large universes.



        The `/cross-sectional` endpoint supports Long Running asynchronous
        requests up to **10 minutes** via the `batch` parameter. *This feature
        is available to Individual Users subscribed to the Performance Package
        and Performance Package Plus Performance Tiers and all Production Users.
        If you are unsure which Performance Tier you are subscribed to or you
        would like to gain access to the batch capabilities, please contact your
        FactSet Account Team or "Report Issue" above and our support teams can
        assist.*


        ***


        ### Iterated Cross-Sectional Functionality



        This endpoint supports the ability to automatically iterate through
        different cross sections over time. The **Iterated Cross-Sectional
        Functionality (ICSF)** expands the Cross-Sectional endpoint to support
        retrieving data items for *multiple dates*, allowing users to take
        advantage of the Screening engine’s efficiency even when history is
        required. 



        Use the parameters `startDate`, `endDate`, and `frequency` in the
        Cross-Sectional endpoint to provide your desired dates. Specify “0” in
        date argument of the Screening formulas provided in the formulas
        parameter and/or the universe parameter. Lastly, the Iterated
        Cross-Sectional Functionality is required to run as a `batch` request.
        Therefore, the batch parameter must be set to “Y”. 



        Access to backtesting and batch functionality is required to leverage
        the Iterated Cross-Sectional Functionality. 


        **When to use ICSF:**


        The ICSF can offer better performance than Time-Series requests when the
        date range is relatively small, and so it is recommended to use ICSF if
        the number of IDs requested is greater than the number of dates. If the
        number of dates is greater than the number of IDs in the request, it is
        recommended to use Time-Series.


        *Note: This is a general rule of thumb and performance may vary
        depending on the formulas in use.*
      tags:
        - Retrieve
        - Data
        - Items
        - Screening
        - Formulas)
        - For
        - List
        - Of
        - Identifiers
        - Or
        - Defined
        - Universe.
        - V1
        - Time
        - Series
        - Cross
        - Sectional
    post:
      summary: >-
        Retrieve data items (Screening formulas) for a list of identifiers or
        defined universe.
      description: >
        The `/cross-sectional` endpoint is closely aligned with FactSet’s
        powerful data retrieval **Screening language** which is optimized for
        analysis of data items at single point in time for different entities
        and is extremely efficient for large universes.



        The `/cross-sectional` endpoint supports Long Running asynchronous
        requests up to **10 minutes** via the `batch` parameter. *This feature
        is available to Individual Users subscribed to the Performance Package
        and Performance Package Plus Performance Tiers and all Production Users.
        If you are unsure which Performance Tier you are subscribed to or you
        would like to gain access to the batch capabilities, please contact your
        FactSet Account Team or "Report Issue" above and our support teams can
        assist.*


        ***


        ### Iterated Cross-Sectional Functionality



        This endpoint supports the ability to automatically iterate through
        different cross sections over time. The **Iterated Cross-Sectional
        Functionality (ICSF)** expands the Cross-Sectional endpoint to support
        retrieving data items for *multiple dates*, allowing users to take
        advantage of the Screening engine’s efficiency even when history is
        required. 



        Use the parameters `startDate`, `endDate`, and `frequency` in the
        Cross-Sectional endpoint to provide your desired dates. Specify “0” in
        date argument of the Screening formulas provided in the formulas
        parameter and/or the universe parameter. Lastly, the Iterated
        Cross-Sectional Functionality is required to run as a `batch` request.
        Therefore, the batch parameter must be set to “Y”. 



        Access to backtesting and batch functionality is required to leverage
        the Iterated Cross-Sectional Functionality. 


        **When to use ICSF:**


        The ICSF can offer better performance than Time-Series requests when the
        date range is relatively small, and so it is recommended to use ICSF if
        the number of IDs requested is greater than the number of dates. If the
        number of dates is greater than the number of IDs in the request, it is
        recommended to use Time-Series. 


        *Note: This is a general rule of thumb and performance may vary
        depending on the formulas in use.*
      tags:
        - Retrieve
        - Data
        - Items
        - Screening
        - Formulas)
        - For
        - List
        - Of
        - Identifiers
        - Or
        - Defined
        - Universe.
        - V1
        - Time
        - Series
        - Cross
        - Sectional
  /v1/batch-status:
    get:
      summary: Returns the status for a Batch Request
      description: >
        Return the status for the underlying batch request that is specified by
        the id.

          The Formula API supports Long Running asynchronous requests up to **20 minutes** via the `batch` parameter in the `/time-series` endpoint and up to **10 minutes** in the `/cross-sectional` endpoint.

          *This feature is available to Individual Users subscribed to the Performance Package and Performance Package Plus Performance Tiers and all Production Users. If you are unsure which Performance Tier you are subscribed to or you would like to gain access to the batch capabilities, please contact your FactSet Account Team or "Report Issue" above and our support teams can assist.*
      tags:
        - Returns
        - The
        - Status
        - For
        - Batch
        - Request
        - V1
        - Time
        - Series
        - Cross
        - Sectional
        - Batch
        - Status
    post:
      summary: Returns the status for a Batch Request
      description: >
        Return the status for the underlying batch request that is specified by
        the id.

          The Formula API supports Long Running asynchronous requests up to **20 minutes** via the `batch` parameter in the `/time-series` endpoint and up to **10 minutes** in the `/cross-sectional` endpoint.

          *This feature is available to Individual Users subscribed to the Performance Package and Performance Package Plus Performance Tiers and all Production Users. If you are unsure which Performance Tier you are subscribed to or you would like to gain access to the batch capabilities, please contact your FactSet Account Team or "Report Issue" above and our support teams can assist.*
      tags:
        - Returns
        - The
        - Status
        - For
        - Batch
        - Request
        - V1
        - Time
        - Series
        - Cross
        - Sectional
        - Batch
        - Status
  /v1/batch-result:
    get:
      summary: Returns the response for a Batch Request
      description: >
        Returns the response data for the underlying batch request that is
        specified by the id.

          The Formula API supports Long Running asynchronous requests up to **20 minutes** via the `batch` parameter in the `/time-series` endpoint and up to **10 minutes** in the `/cross-sectional` endpoint.

          *This feature is available to Individual Users subscribed to the Performance Package and Performance Package Plus Performance Tiers and all Production Users. If you are unsure which Performance Tier you are subscribed to or you would like to gain access to the batch capabilities, please contact your FactSet Account Team or "Report Issue" above and our support teams can assist.*
      tags:
        - Returns
        - The
        - Response
        - For
        - Batch
        - Request
        - V1
        - Time
        - Series
        - Cross
        - Sectional
        - Batch
        - Status
        - Result
    post:
      summary: Returns the status for a Batch Request
      description: >
        Returns the response data for the underlying batch request that is
        specified by the id.

          The Formula API supports Long Running asynchronous requests up to **20 minutes** via the `batch` parameter in the `/time-series` endpoint and up to **10 minutes** in the `/cross-sectional` endpoint.

          *This feature is available to Individual Users subscribed to the Performance Package and Performance Package Plus Performance Tiers and all Production Users. If you are unsure which Performance Tier you are subscribed to or you would like to gain access to the batch capabilities, please contact your FactSet Account Team or "Report Issue" above and our support teams can assist.*
      tags:
        - Returns
        - The
        - Status
        - For
        - Batch
        - Request
        - V1
        - Time
        - Series
        - Cross
        - Sectional
        - Batch
        - Status
        - Resu
